<?php

/**
 * Implements hook_schema().
 */
function hosting_restapi_schema() {
  $schema = array();

  $schema['hosting_restapi_order'] = array(
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'site' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'current_status' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'updated' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'invoice_id' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'token' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'ip' => array(
        'type' => 'varchar',
        'length' => 64,
        'not null' => TRUE,
      ),
      'crmhost' => array(
        'type' => 'varchar',
        'length' => 128,
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array('invoice_id' => array('invoice_id')),
  );

  $schema['hosting_restapi_log'] = array(
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'order_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'task' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'message' => array(
        'type' => 'text',
        'not null' => TRUE,
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('id'),
  );

  return $schema;
}

/**
 * Add the crmhost column.
 */
function hosting_restapi_update_7101() {
  db_add_field('hosting_restapi_order', 'crmhost', [
    'type' => 'varchar',
    'length' => 128,
    'default' => '',
  ]);
}
