<?php

/**
 * Implements hook_hosting_restapi_validate_id()
 */
function hosting_restapi_civi_hosting_restapi_validate_id($invoice_id) {
  watchdog('hosting_restapi_civi', 'hosting_restapi_civi_hosting_restapi_validate_id');

  // Check that the invoice_id is legit...
  require_once drupal_get_path('module', 'hosting_restapi_civi') . '/civicrm.api.php';
  $api = new civicrm_api3(array(
    'server' => variable_get('hosting_restapi_crmhost', NULL),
    'api_key' => variable_get('hosting_restapi_crmapikey', NULL),
    'key' => variable_get('hosting_restapi_crmkey', NULL),
  ));

  $api->Contribution->Get(array('invoice_id' => $invoice_id));

  if ($api->count == 1) {
    return TRUE;
  }
  else {
    throw new Exception('Could not lookup invoice.');
  }
}

/**
 * Implements hook_hosting_restapi_check_access()
 */
function hosting_restapi_civi_hosting_restapi_check_access($key = NULL, $secret = NULL) {
  watchdog('hosting_restapi_civi', 'hosting_restapi_civi_hosting_restapi_check_access');

  return TRUE; // TODO: Fixme.
  // Not sure what to do with this, this whole check was commented out in the original code

  global $civicrmhosting_key;
  global $civicrmhosting_secret;

  if (empty($key) || empty($secret)) {
    throw new Exception('Access denied. Missing credentials.');
  }

  if ($key != $civicrmhosting_key && $secret != $civicrmhosting_secret) {
    throw new Exception('Access denied. Invalid credentials.');
  }

  return TRUE;
}
