<?php

/**
 * Implements hook_hosting_restapi_validate_invoice_id().
 *
 * TODO: document.
 */
function hosting_restapi_civicrm_hosting_restapi_validate_invoice_id($invoice_id) {
  // Lookup the invoice_id in CiviCRM
  // Using the API from the "symbiocivicrm" extension because Stripe stores both the payment
  // intent and the confirmation in the trxn_id field, which causes problems with Contribution.get.
  $api = hosting_restapi_civicrm_api($invoice_id);
  $api->Symbiocivicrm->Getconfig([
    'invoice_id' => $invoice_id,
  ]);
  if (!empty($api->values['site']['name'])) {
    return TRUE;
  }
  throw new Exception('Could not lookup invoice.');
}

/**
 * Implements hook_hosting_restapi_check_access()
 */
function hosting_restapi_civicrm_hosting_restapi_check_access($key = NULL, $secret = NULL) {
  watchdog('hosting_restapi_civicrm', 'hosting_restapi_civicrm_hosting_restapi_check_access');

  return TRUE; // TODO: Fixme.

  // Not sure what to do with this, this whole check was commented out in the original code

  global $civicrmhosting_key;
  global $civicrmhosting_secret;

  if (empty($key) || empty($secret)) {
    throw new Exception('Access denied. Missing credentials.');
  }

  if ($key != $civicrmhosting_key && $secret != $civicrmhosting_secret) {
    throw new Exception('Access denied. Invalid credentials.');
  }

  return TRUE;
}

/**
 * Returns a CiviCRM REST API object.
 */
function & hosting_restapi_civicrm_api($invoice_id) {
  require_once drupal_get_path('module', 'hosting_restapi_civicrm') . '/civicrm.api.php';
  $crmhost = db_query("SELECT crmhost FROM hosting_restapi_order WHERE invoice_id = :invoice_id", [':invoice_id' => $invoice_id])->fetchField();
  $api = new civicrm_api3([
    'server' => $crmhost,
    // user key
    'api_key' => variable_get('hosting_restapi_crmapikey', NULL),
    'site_key' => variable_get('hosting_restapi_crmkey', NULL),
  ]);
  return $api;
}

/**
 * Sets the hosting_restapi_token in var in the inventory.
 *
 * Implements hook_ansible_inventory_alter from the 'aegir_ansible' module
 *
 * @see https://www.drupal.org/project/aegir_ansible/
 */
function hosting_restapi_civicrm_ansible_inventory_alter(&$inventory) {
  $nids = !empty($_REQUEST['include_disabled']) ? hosting_civicrm_ansible_get_all_sites() : hosting_civicrm_get_sites();
  $civicrm_nodes = node_load_multiple($nids);
  foreach ($civicrm_nodes as $node) {
    // This should be set by hosting_civicrm_ansible
    if (empty($inventory->{'_meta'}->hostvars->{$node->title})) {
      $inventory->{'_meta'}->hostvars->{$node->title} = [];
    }
    $inventory->{'_meta'}->hostvars->{$node->title}['hosting_restapi_token'] = hosting_restapi_get_token_for_url($node->title);
  }
}
